---
title: "Test Script"
author: "Connor Quiroz"
date: "2025-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(arrow)
library(rfishbase)
library(duckdbfs)
library(rfishbase)
library(tidyverse)
library(cowplot)


# Load in packages needed for ARTIS
library(devtools)
library(tidytext)
# devtools::install_github("davidsjoberg/ggsankey")
library(ggsankey)
# devtools::install_github("Seafood-Globalization-Lab/exploreARTIS@v1.0.0", dependencies = TRUE)
library(exploreARTIS)
```

```{r consumption data}
consumption <- read_parquet("../data/consumption/example_consumption_eez_2024_12_06.parquet")

sciname <- read.csv("../data/consumption/sciname.csv")

consumption_joined <- left_join(consumption, sciname, by = c("sciname_hs_modified" = "sciname"))

consumption_joined <- consumption_joined %>%
  filter(year == 2019)

USA <- consumption_joined %>%
  filter(year == 2019, consumer_iso3c == "USA")

write_parquet(consumption_joined, "../output/consumption_joined.parquet")
write_parquet(USA, "../output/USA.parquet")

USA %>%
  filter(!is.na(dom_source),
         !is.na(isscaap),
         !str_detect(isscaap, "Multiple ISSCAAP groups")) %>%
  group_by(isscaap) %>%
  summarize(sum = sum(live_weight_t)) %>%
  arrange(-sum) %>%
  top_n(5) %>%
  mutate(isscaap = fct_reorder(isscaap, sum)) %>%
  ggplot(aes(x = sum, y = fct_reorder(isscaap, sum), fill = isscaap)) +
  geom_col() +
  scale_fill_manual(values = artis_palette(9)) +
  theme_cowplot() +
  labs(x = "Consumption (tons)", y = "", fill = "") +
  guides(fill = "none") +
  theme_cowplot()

USA %>%
  filter(!is.na(dom_source),
         !is.na(isscaap),
         !str_detect(isscaap, "Multiple ISSCAAP groups")) %>%
  group_by(dom_source, isscaap) %>%
  summarize(sum = sum(live_weight_t)) %>%
  arrange(-sum) %>%
  top_n(5) %>%
  ggplot(aes(x = sum, y = dom_source, fill = isscaap)) +
  geom_col(position = "fill") +
  scale_fill_manual(values = artis_palette(15)) +
  theme_cowplot() +
  labs(x = "Proportion of consumption", y = "", fill = "")
  

library(ggridges)

seafood_types <- consumption_joined %>%
  filter(!is.na(dom_source),
         !is.na(isscaap),
         !str_detect(isscaap, "Multiple ISSCAAP groups"),
         year == 2019) %>%
  group_by(consumer_iso3c, isscaap) %>%
  summarize(sum = log(sum(live_weight_t))) %>%
  add_region(col = "consumer_iso3c", region.col.name = "region") %>%
  filter(!is.na(region)) %>%
  ungroup() %>%
  distinct(isscaap) %>%
  pull(isscaap)



consumption_joined %>%
  filter(!is.na(dom_source),
         !is.na(isscaap),
         !str_detect(isscaap, "Multiple ISSCAAP groups"),
         year == 2019) %>%
  group_by(consumer_iso3c, isscaap) %>%
  summarize(sum = log(sum(live_weight_t)), .groups = "drop") %>%
  filter(str_detect(isscaap, "fish")) %>%
  add_region(col = "consumer_iso3c", region.col.name = "region") %>%
  ggplot(aes(x = sum, y = region, fill = region)) +
  geom_density_ridges(position = "identity", alpha = 0.4) +
  scale_fill_manual(values = artis_palette(6)) +
  theme_cowplot() +
  guides(fill = "none") +
  labs(x = "Less → more consumption", y = "", title = "Fish") +
  theme(plot.title = element_text(hjust = 0.5))
  
```

